### PR TITLE
Increment one fixed

### LINKED ISSUE #1: As a player, I would want to see a main menu with all the options

### PR DESCRIPTION
**Pull request by Creldra**
#1 #2 #3 
Increment One is ready to merge, please review and approve

### CODE REVIEW

**Review by Keithpek — COMMENTED** [review]
Looks good to me

**Review by Keithpek — APPROVED** [review]
Accidentally left my review as a comment, setting as Approve now

**Review by ChristopherTeyWeixian — APPROVED** [review]
look good to me

**Review by teyzx123 — APPROVED** [review]
Looks good to me

**Pull request merged**
